flowchart TB

    subgraph Measurement
    A[AbstractMeasurementSetting]
    B[LocalUnitaryMeasurementSetting]
    C[ComputationalBasisMeasurementSetting]
    D[MeasurementData]
    E[MeasurementProbability]
    F[MeasurementGroup]

    B --> A
    C --> A
    end

    subgraph ClassicalShadows
    G[AbstractShadow]
    H[DenseShadow]
    I[FactorizedShadow]

    H --> G
    I --> G
    end

    subgraph QuantumInformation
    Q1(get_fidelity)
    Q2(get_trace_moment)
    Q3(get_selfXEB)
    end

    subgraph Estimators
    X1(jackknife)
    X2(bootstrap?)
    end

    %% Optional relationships (e.g., uses or composition):
    D -- uses --> B
    F -- contains --> D